### ISSUE TITLE
npm fails on Windows due to failing to compile zopfli

### ISSUE THREAD

**Issue by andrewkhan1** [bouzuya/rfc6570-expand#1]
Not got much experience with node-gyp, but it's failing on Windows 10 due to failing to compile zopfli.vcxproj. This is with the latest version of node 6 and latest npm.

**Comment by bouzuya** [comment]
I'm sorry. I don't have a windows machine. I can't check it.

**Comment by andrewkhan1** [comment]
I am going to be having another look later. If I can fix it I will do a PR.

**Comment by bouzuya** [comment]
I wait for PR.
